<!-- Go to www.addthis.com/dashboard to customize your tools --> 
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e33d722d0b16430"></script>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<a class="action share" href="#" title="<?= $block->escapeHtml(__('Share')) ?>">
    <span><?= $block->escapeHtml(__('Share')) ?></span>
<div class="addthis_inline_share_toolbox"></div>
</a>
            