<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="customer-welcome dropdown">
    <?php if ($block->isLoggedIn()) : ?>
        <span class="my-account customer-name dropdown-toggle"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true">
            <span>My Account</span>
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?= $block->escapeHtml(__('Change')) ?></span>
            </button>
        </span>
        <ul class="customer-menu dropdown-content" data-target="dropdown">
            <?= $block->getChildHtml(); ?>
        </ul>
    <?php else : ?>
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> class="my-account" title="<?= $block->escapeHtml(__('Login / Sign Up')); ?>"><span><?= $block->escapeHtml(__('Login / Sign Up')); ?></span></a>
    <?php endif; ?>
</li>